export const ActionTypes = {
    CREATE_CONTACT:"CREATE_CONTACT",
    GET_CONTACT :"GET_CONTACT",
    UPDATE_CONTACT:"UPDATE_CONTACT",
    DELETE_CONTACT:"DELETE_CONTACT",
    SELECT_CONTACT:"SELECT_CONTACT",
    CLEAR_CONTACT:"CLEAR_CONTACT",
    DELETE_SELECT_CONTACT:"DELETE_SELECT_CONTACT"
}